apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: synergychat-crawler
  name: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      containers:
        - image: bootdotdev/synergychat-crawler:latest
          name: synergychat-crawler-1
          resources: {}
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
          envFrom:
            - configMapRef:
                name: synergychat-crawler-configmap
        - image: bootdotdev/synergychat-crawler:latest
          name: synergychat-crawler-2
          resources: {}
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
          env:
            - name: CRAWLER_PORT
              valueFrom:
                configMapKeyRef:
                  name: synergychat-crawler-configmap
                  key: CRAWLER_PORT_2
            - name: CRAWLER_DB_PATH
              valueFrom:
                configMapKeyRef:
                  name: synergychat-crawler-configmap
                  key: CRAWLER_DB_PATH
            - name: CRAWLER_KEYWORDS
              valueFrom:
                configMapKeyRef:
                  name: synergychat-crawler-configmap
                  key: CRAWLER_KEYWORDS
        - image: bootdotdev/synergychat-crawler:latest
          name: synergychat-crawler-3
          resources: {}
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
          env:
            - name: CRAWLER_PORT
              valueFrom:
                configMapKeyRef:
                  name: synergychat-crawler-configmap
                  key: CRAWLER_PORT_3
            - name: CRAWLER_DB_PATH
              valueFrom:
                configMapKeyRef:
                  name: synergychat-crawler-configmap
                  key: CRAWLER_DB_PATH
            - name: CRAWLER_KEYWORDS
              valueFrom:
                configMapKeyRef:
                  name: synergychat-crawler-configmap
                  key: CRAWLER_KEYWORDS
      volumes:
        - name: cache-volume
          emptyDir: {}