apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: synergychat-api
  name: synergychat-api
  namespace: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-api
  template:
    metadata:
      labels:
        app: synergychat-api
    spec:
      volumes:
        - name: synergychat-api-volume
          persistentVolumeClaim:
            claimName: synergychat-api-pvc
      containers:
      - name: synergychat-api
        image: bootdotdev/synergychat-api:latest
        volumeMounts:
        - name: synergychat-api-volume
          mountPath: /persist
        resources: {}
        envFrom:
          - configMapRef:
              name: synergychat-api-configmap